#!/bin/sh

adb shell "run-as com.transistorsoft.backgroundgeolocation.ionic2 cat /data/user/0/com.transistorsoft.backgroundgeolocation.ionic2/databases/transistor_logback.db" > transistor_logback.db

